#!/usr/bin/env bash
set -eu

DEST=${1:-"tftpboot"}

if [ ! -d $DEST ]; then
  echo "Creating directory $DEST"
  mkdir -p $DEST
fi

curl -s -o $DEST/undionly.kpxe http://boot.ipxe.org/undionly.kpxe
cp $DEST/undionly.kpxe $DEST/undionly.kpxe.0
curl -s -o $DEST/ipxe.efi http://boot.ipxe.org/ipxe.efi

mkdir -p $DEST/tmp
curl -s -o $DEST/tmp/syslinux.zip https://mirrors.edge.kernel.org/pub/linux/utils/boot/syslinux/syslinux-6.03.zip
pushd $DEST/tmp && unzip syslinux.zip && popd
/bin/cp -f $DEST/tmp/bios/core/lpxelinux.0 $DEST
/bin/cp -f $DEST/tmp/bios/com32/elflink/ldlinux/ldlinux.c32 $DEST
/bin/rm -rf $DEST/tmp
# Any vaguely recent CoreOS grub.efi is fine
curl -s -o $DEST/grub.efi https://stable.release.core-os.net/amd64-usr/1353.7.0/coreos_production_pxe_grub.efi
